### ISSUE TITLE
Batch mode only supports one file?

### ISSUE THREAD

**Issue by alphapapa** [conao3/indent-lint.el#10]
https://github.com/conao3/indent-lint.el/blob/3caa30efd743ed5c9da36d9e2968a304a133c8a1/indent-lint.el#L256

It seems that the batch command only checks the first file provided on the command line.  Some other tools, like `package-lint-batch-and-exit`, process all of the files remaining.

Thanks.

**Comment by conao3** [comment]
Good suggestion! I'll support this.

**Comment by alphapapa** [comment]
Thanks.

**Comment by conao3** [comment]
Your welcome!
