### ISSUE TITLE
Copy major-mode interactively

### ISSUE THREAD

**Issue by DamienCassou** [conao3/indent-lint.el#3]
When indent-lint is used interactively, I guess you could copy the origin's buffer `major-mode` to the temporary buffer. This will make sure the same major-mode is used, regardless of what `normal-mode` says it should be.

But this won't be enough because the origin file could have some file-local variables that need to be set in the temp buffer too. For this to work reliably, I would try something like this instead:

1. copy the content of the origin buffer to a temporary buffer
2. indent the origin buffer (that way you are sure you have the same major-mode and local variables)
3. diff the 2 buffers
4. copy the content of the temporary buffer to the origin buffer

You should make sure step (4) always happens so I would wrap all of it inside an `unwind-protect`.

I'm not sure it's going to work but it's probably worth trying.

**Comment by conao3** [comment]
Your concerns are reasonable, I design this package for *general* indent linter.

In the case of Elisp, the same indent result can be obtained in many cases by setting to `emacs-lisp-mode`, but there are many variables to adjust indent in `cc-mode`, and the same indent result is obtained in various environments Is not easy.

However, if only buffer local variables affect indentation, we can get a list of them with `(buffer-local-variables)`.
When assuming a large buffer, I cannot measure the effects of temporarily changing the buffer that the user is editing (like Web-mode in Elisp).

First, I try apply major-mode and copy buffer-local method.

**Comment by conao3** [comment]
I had rewritten the whole package using async-await. Please review again, @DamienCassou?

**Comment by DamienCassou** [comment]
I don't know the promise/async-await APIs so I won't help with that.

- why do you set `(normal-mode)` before setting the original `major-mode`?
- `make-temp-file` creates files outside the working directory which means the indentation function might see different variable values if directory-local variables are in use.
- the functions are much longer than before, making it hard to review. I suggest splitting into many smaller ones.

**Comment by conao3** [comment]
1. To read and load the buffer-local variable wrote footer of file.
  But this loading can omit if inherit original buffer-local variable.
```diff
modified   indent-lint.el
@@ -87,8 +87,12 @@ Function will be called with 2 variables; `(,raw-buffer ,indent-buffer)."
          (with-temp-file ,dest-file
            (insert-file-contents ,src-file)
            (let ((buffer-file-name ,(buffer-name buf)))
-             (normal-mode)
              (funcall #',(with-current-buffer buf major-mode))
+             (dolist (argcell ',(with-current-buffer buf (buffer-local-variables)))
+               (let ((arg (car argcell))
+                     (val (cdr argcell)))
+                 (ignore-errors
+                     (set arg val))))
              (indent-region (point-min) (point-max)))))))
    (lambda (res)
      (promise-resolve res))
```
  But this approach is failed maybe cannot a readable object has injected.
```
Warning (emacs): Fail indent
  buffer: #<buffer indent-lint.el>
  major-mode: emacs-lisp-mode
  src-file: /tmp/emacs-indent-lintQQeIyE
  dest-file: /tmp/emacs-indent-lint9B1Ecf
  reason: (invalid-read-syntax "#")
```

2. Inherit all buffer-local variables to temp buffer include directory-local variables? (I don't know this deeply.)
3. All functions are less than display height. So, there is no need to split into many smaller ones.

**Comment by DamienCassou** [comment]
`(buffer-local-variables)` should be fine.

**Comment by conao3** [comment]
As #5 merged, this issue solved.
